# Generated by Django 4.2.5 on 2023-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(),
        ),
    ]
